version: '3'
services:
  eventstore_seed:
    image: cassandra:latest
    ports:
      - '7000-7001:7000-7001'
      - '7199:7199'
      - '9042:9042'
      - '9160:9160'
    restart: always
    deploy:
      restart_policy: 
        condition: any
      mode: global

  eventstore_node:
    image: cassandra:latest
    links:
      - eventstore_seed
    environment:    
      - CASSANDRA_SEEDS=eventstore_seed
    depends_on:
      - eventstore_seed
    restart: always
    deploy:
      restart_policy:
        condition: any
        delay: 5s
      replicas: 2
